#!/usr/bin/python3

fh = open('./f2', 'r')
n = 5
code = ''
# fh = ['ULL', 'RRDDD', 'LURDL', 'UUUUD']
for line in fh:
    for d in line:
        if d == 'D' and (n + 3) < 10:
            n += 3
        elif d == 'R' and (n + 1) not in [1, 4, 7, 10]:
            n += 1
        elif d == 'U' and (n - 3) > 0:
            n -= 3
        elif d == 'L' and (n - 1) not in [0, 3, 6, 9]:
            n -= 1
        print(n)
    code += str(n)

print("code = %s" % code)


# part2
#     1
#   2 3 4
# 5 6 7 8 9
#   A B C
#     D
kp = {'1': {'U': '1', 'R': '1', 'D': '3', 'L': '1'},
      '2': {'U': '2', 'R': '3', 'D': '6', 'L': '2'},
      '3': {'U': '1', 'R': '4', 'D': '7', 'L': '2'},
      '4': {'U': '4', 'R': '4', 'D': '8', 'L': '3'},
      '5': {'U': '5', 'R': '6', 'D': '5', 'L': '5'},
      '6': {'U': '2', 'R': '7', 'D': 'A', 'L': '5'},
      '7': {'U': '3', 'R': '8', 'D': 'B', 'L': '6'},
      '8': {'U': '4', 'R': '9', 'D': 'C', 'L': '7'},
      '9': {'U': '9', 'R': '9', 'D': '9', 'L': '8'},
      'A': {'U': '6', 'R': 'B', 'D': 'A', 'L': 'A'},
      'B': {'U': '7', 'R': 'C', 'D': 'D', 'L': 'A'},
      'C': {'U': '8', 'R': 'C', 'D': 'C', 'L': 'B'},
      'D': {'U': 'B', 'R': 'D', 'D': 'D', 'L': 'D'}
      }


fh = open('./f2', 'r')
# fh = ['ULL', 'RRDDD', 'LURDL', 'UUUUD']
code = ''
s = '5'
# fh = ['ULL', 'RRDDD', 'LURDL', 'UUUUD']
for line in fh:
    for d in line.strip():
        s = kp[s][d]
    code += s

print("code = %s" % code)
